### ISSUE TITLE
missing variants in 'weights.UKB.'

### ISSUE THREAD

**Issue by gbloeb** [omerwe/polyfun#100]
Is there a reason why there are variants not present in the provided UKB weights files that are present in the provided UKB LD scores and baseline annotations?  

For instance for chromosome 1 there are 1,542,314 variants in the 'baselineLF2.2.UKB.1.l2.ldscore.parquet' and 'baselineLF2.2.UKB.1.annot.parquet' files but only 1,444,009 in weights.UKB.1.l2.ldscore.parquet.

Thanks so much for clarifying!

**Comment by omerwe** [comment]
It's been a few years since I created these, but I think this is because some SNPs have INFO score <0.6. I included all SNPs with MAF>0.1% in the .annot files (regardless of their INFO score), but I didn't include SNPs with INFO<0.6 in the weights files (since the weights files only need to include SNPs for which we also have sumstats, and we only used sumstats for SNPs with INFO >= 0.6).

**Comment by gbloeb** [comment]
Thanks!
