### ISSUE TITLE
Assertion Error when using functional susie fine mappping

### ISSUE THREAD

**Issue by dietina** [omerwe/polyfun#116]
Hi Omer,

Can I know if we have some advice on how to fix this AssertionError ? :
------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/filepath/finemapper.py", line 1262, in <module>
    residual_var=args.susie_resvar, residual_var_init=args.susie_resvar_init, hess_resvar=args.susie_resvar_hess)
  File "/filepath/finemapper.py", line 743, in finemap
    assert np.isclose(prior_weights.sum(), 1)
AssertionError
------------------------------------------------------------------------------------------------------------------------------
I used functional susie finemapping, and this issue happens in some certain CHRs, for example, CHR6 and CHR1, but it worked for CHR2 and CHR5. 
I have not encountered the issue when I ran non-functional susie finemapping for all CHRs(1-22).   

Any advice would be appreciated! Thank you in advance Omer.

**Comment by omerwe** [comment]
@dietina, you can send example data to omer.we@gmail.com.
I suspect that this is somehow related to long-range LD regions: Both chromosomes 6 and 11 have such regions (as well as chromosome 8). However, I'm not aware of any long-range LD regions for chromosome 1...

**Comment by liqingbioinfo** [comment]
May I know the follow-ups for this issue? I encountered the same problem for chromosome 6. Is there any way to fix it?

**Comment by omerwe** [comment]
@liqingbioinfo please feel free to send me a reproducible example, and I'll try looking into it

**Comment by dietina** [comment]
Hi Omer and Liqing, sorry I was not able to login during the past days. This issue has not been fixed. I will come up with the example and send this to Omer. I am sorry for the delay. 
Can I know if there is any updates that may help with the issue? Thank you! @omerwe @liqingbioinfo

**Comment by omerwe** [comment]
Sorry, I can't do anything until I have a reproducible example in hand...

**Comment by keyrunad** [comment]
I have the same error for the job below:

`python3 finemapper.py --chr 1 --geno ../1000G_EUR_Phase3_plink/1000G.EUR.QC.1 --start 140000001 --end 143000001 --out ../outputs/polyfun_all.chr1.140000001_143000001.gz --method susie --sumstats ../polyfun_sumstats --n 321498 --memory 1 --max-num-causal 5 --allow-missing`

The reason seems to be `df_sumstats_locus` not having any rows except the header causing `prior_weights` at line 749 of `finemapper.py` to be empty and its sum to be 0. Happy to provide any other details if needed. Thanks in advance for all your help!

**Comment by omerwe** [comment]
@keyrunad thanks for looking into this. I updated the code to verify that df_sumstats_locus is not empty, which should at least print a more relevant error message (can you please git pull and make sure that it does)?

However, I still don't know where the error is coming from. I suspect that it's because the SNPs in the LD file and in the sumstats file are inconsistent, but I can't say more until I see a reproducible example, or at least a snapshot of the relevant files. If you can send these to me (see my email address at previous messages in this thread) that would be great.

**Comment by noeri-mohamed-hoesein** [comment]
If this email omer.we@gmail.com is still in use I can send you the data with which I got this error

**Comment by omerwe** [comment]
sure
