### ISSUE TITLE
about missing annotations for rare variants

### ISSUE THREAD

**Issue by szhan1000** [omerwe/polyfun#126]
Dear Omer,

I am planning to apply PolyFun + SuSiE by including our own functional annotation data (~10 different types) predicted by deep learning model. However, we only have predictions for common SNPs (particularly ~10 millions annotation SNPs for the standard S-LSDC) and not for rare variants. I wonder if I should change the v.2.2.UKB of the baseline-LF model to include only common SNPs?  or is there anyway I can include functional annotations that are only available for certain MAF classes (e.g. common SNPs). The GWAS summary statistics I am trying to fine map is schizophrenia PGC3 that include only common SNPs (MAF>0.01).

Any advice will be appreciated!

Thanks,
Shizhong

**Comment by omerwe** [comment]
Hi @szhan1000,

This is a good question -- what you're asking is more conceptual than technical. If you're going to apply fine-mapping using only common SNPs, there's a good chance that you'll get wrong results because the true causal SNPs are not in the data... I'm afraid I can't help with this issue --- fine-mapping ideally needs access to rare SNPs.

Technically, you need to make a decision how you want to treat rare SNPs. You can either exclude them (and face the consequences I mentioned above) or you can include them and assume that none of them belongs in any of your predicted annotations. Neither option is perfect, but you need to weight the pros and cons of each approach...

I hope this helps, please let me know if not!

**Comment by szhan1000** [comment]
Hi Omer, thank you for your quick response! I have two thoughts: 1) most GWAS summary statistics, especially those of meta-analysis conducted by large consortium such as PGC, include only common SNPs (MAF>0.01). I think the hypothesis is that most causal variants are still common SNPs, so it will be nice if PolyFun can be adapted to only common SNPs. 2) I am actually not sure about this point, but just a vague feeling, that LD score regression is based on the LD between common SNPs (e.g., Hapmap SNPs) and SNPs within annotation regions. I wonder if rare SNPs within annotation regions could contribute very little to the LD score, and thus will not contribute much to the heritability estimation?
