### ISSUE TITLE
Extracting annotations - including multiple annotation sources in the --annot parameter?

### ISSUE THREAD

**Issue by Diluent67** [omerwe/polyfun#152]
I tried browsing through other issues and couldn't find one logged for this. In extract_annotations.py, the --annot parameter seems to only take in one annotation file. However, I'm using multiple custom annotations as well and would like them to be included in the output. I don't think it's possible to include more than one annotation file in the --annot parameter at the moment. Could this be changed by chance?

**Comment by omerwe** [comment]
@Diluent67 That's true. Unfortunately I don't have the bandwidth to fix this (the fix is simple but I don't have the time to test that I didn't make a silly mistake). The workaround is to run `extract_annotations.py` for each annotation file separately, and then manually concatenate the output files. Sorry I can't be more helpful...
