### ISSUE TITLE
UKBB Annotation files missing A1, A2 columns

### ISSUE THREAD

**Issue by taboltz** [omerwe/polyfun#159]
Hello! I'm interested in using the UKBB functional annotations as downloaded from here (https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD/baselineLF_v2.2.UKB.tar.gz ) though I noticed that the .parquet files are not in the baselineLF UKB tarball. The UKBB annotation link provided here (https://github.com/omerwe/polyfun/wiki/2.-Using-and-creating-functional-annotations) mentions that the download requires 30BG, though this link only expands out to ~12GB after downloading and extracting the file contents. 

The .annot.gz and the .ldscore.gz files do not have the A1 and A2 columns, and when trying to run polyfun, we get the following errors: 

```
[ERROR] baselineLF_v2.2.UKB/baselineLF2.2.UKB.1.annot.gz has a missing column: A1
[ERROR] baselineLF_v2.2.UKB/baselineLF2.2.UKB.1.annot.gz has a missing column: A2
 
```

I'm working with @mkoromina to test out her Snakemake pipeline, and we were hoping to get your advice on this error! Thank you so much for your time and any help you may be able to provide.

**Comment by omerwe** [comment]
@taboltz thanks for the report!
After some internal investigation, it turns out I accidentally linked to the wrong tar.gz file when we did our large file rearrangement two months ago. Sorry for that!

We're working on fixing this --- we need to transfer the correct .tar.gz file to the AWS S3 bucket. Hopefully we'll do that  early next week. I'll update here when it's done.

Thanks again, sorry for the trouble, and hope things will be sorted out soon.

**Comment by omerwe** [comment]
@taboltz we finally got this sorted out, sorry for the delay!
I updated the link in [the wiki page](https://github.com/omerwe/polyfun/wiki/2.-Using-and-creating-functional-annotations). It now points to [the correct annotations file](https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD/baselineLF_v2.2.UKB.polyfun.tar.gz). I hope this resolves your issues, please let me know if not (and close the issue if it does).

**Comment by taboltz** [comment]
the new link works, thank you so much for your help!
