### ISSUE TITLE
negative weights appear in the. mixweights file without arg --allow-neg-mixweights

### ISSUE THREAD

**Issue by Y-Isaac** [omerwe/polyfun#196]
HI,@omerwe

Currently I found that even if I didn't specify the _--allow-neg-mixweights_ parameter, negative weights still appear in the _.mixweights_ file. Can you please check it?

**Comment by omerwe** [comment]
@Y-Isaac thanks for flagging this. This is actually the intended behavior after the update. The reason is that sometimes the PRS itself is negatively correlated to the phenotype used for estimating mixing weight. So the mixing weight is negative with respect to PRS, but is in fact positive with respect to the flipped PRS. I realize this is somewhat incoherent, but this is how the code works at the moment.

**Comment by Y-Isaac** [comment]
@omerwe Thanks for explanation!
