### ISSUE TITLE
`compression = None` on line 193 of parse.py

### ISSUE THREAD

**Issue by davidaknowles** [omerwe/polyfun#22]
Is this deliberate? It seems to mean you can't read compressed files since it overrides the automatic compression detection.

**Comment by omerwe** [comment]
Thanks for the question. I'm pretty sure that this flag is irrelevant
because pandas can infer compression automatically (this code is taken
directly from ldsc, which was written ~6 years ago before pandas could do
this). Do you have an example where this flag is required? I just verified
that the code can work with .gzipped files on my system (using pandas
0.25.3, though support for compressed files existed for several years I
think).

**Comment by davidaknowles** [comment]
The problem is `compression = None` gets passed to pandas which overrides the auto compression-type detection (at least on my system). The `compression = "infer"` is the default for pd.read_csv.

**Comment by omerwe** [comment]
You're right, my bad --- my test was incorrect. I just pushed an updated
version that disables this line (I made sure that I can now read gzipped
ldscore files). Hope it's fine now!
