### ISSUE TITLE
finemapper.py BGEN files

### ISSUE THREAD

**Issue by zhangpicb** [omerwe/polyfun#68]
Hi!
Thanks for your wonderful code!
I want to know  is LD matrix produced by LDstorev2 different from produced by Plink?
So I want to use LDstore v2 ,so I converted example date to BGEN1.2 format.
And I got this message
```
[ERROR]  Error : The database file is locked (using BGEN index file '/home/polyfun_finemapper_test/ldstore/chr1.bgen.bgi')!

```

My shell code,
```
plink2 --bfile example_data/chr1 --export bgen-1.2 --out chr1

bgenix -index -g chr1.bgen

mkdir -p LD_cache
mkdir -p output

python finemapper.py \
    --geno chr1.bgen \
    --sample-file chr1.sample \
    --sumstats example_data/chr1.finemap_sumstats.txt.gz \
    --n 383290 \
    --chr 1 \
    --start 46000001 \
    --end 49000001 \
    --method finemap \
    --finemap-exe finemap_v1.4_x86_64 \
    --ldstore2 ldstore_v2.0_x86_64 \
    --max-num-causal 5 \
    --cache-dir LD_cache \
    --out output/finemap.finemap_exe.1.46000001.49000001.gz
```
Thanks in advanced!

**Comment by AlisaBIG** [comment]
Hi，Omer！I met the same problem. I wan to calculate LD matrix  using LDstore, but got error message: Error : SNP with rsID '12:89675376:A:G' in file 'chr12_block167.z' could not be matched with SNP in BGEN file 'chr12_block167.bgen'! However  chromosome id  and rsid are same in  my BGEN file and Z file.  Do you know where the problem is?

**Comment by omerwe** [comment]
Hi @AlisaBIG, I'm not sure what's causing the problem. 
Can you please add the flag --verbose to your command, and copy-paste the entire output?
