### ISSUE TITLE
FINEMAP CS coverage

### ISSUE THREAD

**Issue by Ojami** [omerwe/polyfun#84]
Hi Omer,

I know this issue relates to finemapper tool options rather polyfun finemapper. However, I see that while susie outputs 95% credible sets, FINEMAP CSs do not necessarily cover 95% (in my case, almost always below 95%). This is strange, especially that FINEMAP default options should be 95%.
So, would you please let me know whether this is a bug with finemapper or the default behavior of FINEMAP itself?

Thanks!

**Comment by omerwe** [comment]
Hi @Ojami ,

This is probably related to FINEMAP, because the finemapper script just takes the 95% CS results as is. However, can you please explain what you mean by saying that FINEMAP CS don't cover 95%?

**Comment by Ojami** [comment]
I meant for some regions, the sum of PIPs within each FINEMAP CS is < 0.95, while for SuSiE it's always (except those with purity adjustments) >= 0.95. If this happens for SuSiE it's due to purity adjustment (mixture of low/high LD SNPs), but since FINEMAP doesn't implement such an adjustment, it's strange to see this behavior. 
I then close this issue, and still I can't figure out the reason, but seems to be an issue with FINEMAP. As a further sanity check, I'll try to run the FINEMAP with default priors (not via finemapper module) as well.

Thanks!

**Comment by omerwe** [comment]
Hi @Ojami,

Please note that there are several subtle issues here:
1. FINEMAP and SuSiE use different definitions of credible set (see the PolyFun paper for a brief discussion of this)
2. For both FINEMAP and SuSiE, the definition of a 95% credible set is **not** necessarily that the sum of the PIPs should reach 0.95. In the case of FINEMAP, the goal is to choose a set of SNPs whose **joint posterior probability of all being causal** is >0.95. The sum of the PIPs is different from the joint posterior probability, because each PIP is a marginal posterior probability for a single SNP.

**Comment by Ojami** [comment]
Oh, I see now!

Many thanks for the clear explanation! That makes sense now.

Best/Oveis
